# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BqR6Hl1UjP0O6oMiQmfzKkK00YyGd2o
"""

!pip install simpy

import simpy
import random
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, r2_score

def bank_simulation(env, arrival_interval, service_time, wait_times):
    server = simpy.Resource(env, capacity=1)

    def customer(env, name, server):
        arrival_time = env.now
        yield env.timeout(random.expovariate(1.0 / arrival_interval))
        with server.request() as request:
            yield request
            wait_times.append(env.now - arrival_time)
            yield env.timeout(random.expovariate(1.0 / service_time))

    for i in range(100):
        env.process(customer(env, i, server))
    env.run()


data = []
for _ in range(1000):
    avg_arrival = random.uniform(2.0, 10.0)
    avg_service = random.uniform(1.0, 1.9)

    wait_times = []
    env = simpy.Environment()
    bank_simulation(env, avg_arrival, avg_service, wait_times)

    avg_wait = np.mean(wait_times) if wait_times else 0
    data.append([avg_arrival, avg_service, avg_wait])

df = pd.DataFrame(data, columns=['Arrival_Interval', 'Service_Time', 'Avg_Wait_Time'])

X = df[['Arrival_Interval', 'Service_Time']]
y = df['Avg_Wait_Time']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=100),
    "Gradient Boosting": GradientBoostingRegressor(),
    "K-Nearest Neighbors": KNeighborsRegressor()
}

results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    mae = mean_absolute_error(y_test, preds)
    r2 = r2_score(y_test, preds)
    results.append({"Model": name, "MAE": round(mae, 4), "R2 Score": round(r2, 4)})

comparison_df = pd.DataFrame(results).sort_values(by="R2 Score", ascending=False)
print("\n Model Comparison Table")
print(comparison_df.to_string(index=False))

best_model = comparison_df.iloc[0]['Model']
print(f"\nBest Model: {best_model}")